ENVIRONMENT:
  MAX_EPISODE_STEPS: 500
SIMULATOR:
  AGENT_0:
    SENSORS: [RGB_SENSOR, DEPTH_SENSOR]
  FORWARD_STEP_SIZE: 0.25
  TURN_ANGLE: 15
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
    ALLOW_SLIDING: True
  RGB_SENSOR:
    WIDTH: 224
    HEIGHT: 224
    HFOV: 90
    TYPE: HabitatSimRGBSensor
  DEPTH_SENSOR:
    WIDTH: 256  # pretrained DDPPO resnet needs 256x256
    HEIGHT: 256
TASK:
  TYPE: NavigatorTask-v0
  SUCCESS_DISTANCE: 1.0
  SENSORS: [
    "POINTGOAL_WITH_GPS_COMPASS_SENSOR",
  ]
  POINTGOAL_SENSOR:
    GOAL_FORMAT: POLAR
    DIMENSIONALITY: 2
  GOAL_SENSOR_UUID: "pointgoal_with_gps_compass"
  POSSIBLE_ACTIONS: [STOP, MOVE_FORWARD, TURN_LEFT, TURN_RIGHT]
  MEASUREMENTS: [
    DISTANCE_TO_GOAL, 
  ]
  SUCCESS:
    SUCCESS_DISTANCE: 1.0
  SPL:
    SUCCESS_DISTANCE: 1.0
DATASET:
  TYPE: PointNav-v1
  SPLIT: train
  DATA_PATH: data/habitat-test-scenes/v1/{split}/{split}.json.gz
  SCENES_DIR: data/scene_datasets/